#!/usr/bin/env python3
"""Generate a calibration pose set that this arm can actually reach.

Why this exists
---------------
Cartesian poses written by hand (or tuned against a URDF in simulation) are not
necessarily reachable by the real arm: the URDF chain and the arm's internal
MDH flange frame do not have to share a convention, so the same six numbers can
denote different physical poses. When that happens the arm accepts the command,
finds no IK solution, and simply does not move -- with no error to explain it.

This tool sidesteps the problem entirely by working the other way round:

    sample JOINT angles  ->  forward kinematics  ->  Cartesian pose

Every pose it emits is reachable **by construction**, because it was produced
from a joint configuration the arm can hold, using the arm's own MDH table.

It seeds from the arm's CURRENT configuration, so if you first position the arm
where the marker is nicely in view, the generated set keeps the marker roughly
in view too.

Usage
-----
    # 1. hand-guide / jog the arm until the marker fills the camera view
    # 2. generate a pose set around that configuration
    ros2 run piper_auto_handeye generate_poses --can-port can0
    # 3. review, then install it
    ros2 run piper_auto_handeye generate_poses --out src/.../calibration_poses.yaml

Read-only with respect to the arm: it never enables or commands motion.
"""

import argparse
import math
import sys
import time

import numpy as np

from .agx_kinematics import (JOINT_LIMITS, fk, pose_to_xyz_rpy, read_joint_angles)


def _rot_diff_deg(Ta, Tb):
    R = Ta[:3, :3].T @ Tb[:3, :3]
    cos = (np.trace(R) - 1.0) / 2.0
    return math.degrees(math.acos(max(-1.0, min(1.0, cos))))


def generate(seed_q, count, joint_spread_deg, min_rot_deg, max_trans_m,
             position_box, rng, down_cone_deg=None):
    """Sample joint configurations near ``seed_q`` and keep a diverse subset.

    Diversity is what conditions the hand-eye solve: samples that differ only
    in position, or only about one rotation axis, leave the problem
    ill-conditioned no matter how many you take.

    ``down_cone_deg`` keeps every pose LOOKING DOWN: the flange z-axis must
    stay within that many degrees of straight down. For a table-mounted marker
    this is what keeps the marker in view across the whole set -- without it
    the sampler happily wanders into poses staring at the wall.
    """
    lo = np.array([l for l, _ in JOINT_LIMITS])
    hi = np.array([h for _, h in JOINT_LIMITS])
    spread = np.radians(joint_spread_deg)
    seed_T = fk(seed_q)
    seed_t = seed_T[:3, 3]
    cone_cos = None if down_cone_deg is None else math.cos(math.radians(down_cone_deg))

    kept = []            # (q, T)
    attempts = 0
    max_attempts = count * 4000
    while len(kept) < count and attempts < max_attempts:
        attempts += 1
        q = np.clip(seed_q + rng.uniform(-spread, spread, size=len(seed_q)), lo, hi)
        # Stay clear of the mechanical stops: a pose sitting on a limit has no
        # margin for the recovery nudges, and the controller may refuse it.
        if np.any(q < lo + math.radians(3)) or np.any(q > hi - math.radians(3)):
            continue
        T = fk(q)
        t = T[:3, 3]
        if np.linalg.norm(t - seed_t) > max_trans_m:
            continue
        if cone_cos is not None and -T[2, 2] < cone_cos:
            continue                    # flange z-axis strayed too far from down
        if position_box is not None:
            (xlo, ylo, zlo), (xhi, yhi, zhi) = position_box
            if not (xlo <= t[0] <= xhi and ylo <= t[1] <= yhi and zlo <= t[2] <= zhi):
                continue
        # far enough from every pose already kept, in orientation
        if any(_rot_diff_deg(T, Tk) < min_rot_deg for _, Tk in kept):
            continue
        kept.append((q, T))
    return kept, attempts


def to_yaml(kept, speed, settle):
    lines = [
        "# Calibration poses for automatic Eye-in-Hand data collection.",
        "#",
        "# GENERATED by `ros2 run piper_auto_handeye generate_poses`.",
        "#",
        "# These are JOINT-SPACE targets (`joints:`, radians). That is deliberate.",
        "# A Cartesian pose has to be inverted by the arm's controller, and a pose",
        "# a URDF calls reachable need not be reachable in the arm's own kinematic",
        "# model -- when it is not, the arm accepts the command, finds no solution",
        "# and silently does not move. Joint targets have no IK step, so every one",
        "# of these executes as long as it is inside the joint limits, which it is",
        "# by construction: each was sampled in joint space to begin with.",
        "#",
        "# Calibration accuracy is unaffected. The solver consumes the MEASURED",
        "# base_T_gripper from feedback, never the commanded pose; the commanded",
        "# pose only has to be diverse and reachable.",
        "#",
        "# The `position`/`rpy` comment on each entry is the forward kinematics of",
        "# the joint values, for reading only -- it is not used.",
        "#",
        "# Still verify before a live run: reachable does NOT mean collision-free,",
        "# and it does not mean the marker is in view.",
        "/**:",
        "  ros__parameters:",
        "    poses:",
    ]
    for i, (q, T) in enumerate(kept):
        x, y, z, roll, pitch, yaw = pose_to_xyz_rpy(T)
        joints_rad = ", ".join(f"{v:.6f}" for v in q)
        joints_deg = " ".join(f"{math.degrees(v):.1f}" for v in q)
        lines += [
            f"      - name: gen_{i:02d}",
            f"        joints: [{joints_rad}]",
            f"        speed: {speed}",
            f"        settle_time: {settle}",
            f"        # joints (deg): {joints_deg}",
            f"        # flange xyz={x:.3f},{y:.3f},{z:.3f} "
            f"rpy(deg)={math.degrees(roll):.1f},{math.degrees(pitch):.1f},"
            f"{math.degrees(yaw):.1f}",
        ]
    return "\n".join(lines) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Generate reachable calibration poses from the arm's own kinematics.")
    ap.add_argument("--can-port", default="can0")
    ap.add_argument("--count", type=int, default=14,
                    help="how many poses to emit (default 14)")
    ap.add_argument("--joint-spread", type=float, default=18.0,
                    help="deg of joint variation around the current pose (default 18)")
    ap.add_argument("--min-rot", type=float, default=8.0,
                    help="deg of orientation separation required between poses")
    ap.add_argument("--max-trans", type=float, default=0.18,
                    help="m the flange may stray from the current position")
    ap.add_argument("--down-cone", type=float, default=None,
                    help="deg: keep the flange z-axis within this cone of straight "
                         "down (use ~30 for a table-mounted marker)")
    ap.add_argument("--speed", type=float, default=0.15)
    ap.add_argument("--settle", type=float, default=1.0)
    ap.add_argument("--seed", type=int, default=0)
    ap.add_argument("--joints", type=str, default="",
                    help="comma-separated joint angles in deg, instead of reading the arm")
    ap.add_argument("--out", default="",
                    help="write here instead of stdout")
    args = ap.parse_args(argv)

    if args.joints:
        seed_q = np.radians([float(v) for v in args.joints.split(",")])
        print(f"seed joints (deg): {args.joints}", file=sys.stderr)
    else:
        seed_q = read_joint_angles(args.can_port)
        if seed_q is None:
            print(f"ERROR: could not read joint angles from '{args.can_port}'.\n"
                  f"Check the link first:  ros2 run piper_auto_handeye agx_arm_check",
                  file=sys.stderr)
            return 1
        print("seed joints (deg): " +
              ", ".join(f"{math.degrees(v):.1f}" for v in seed_q), file=sys.stderr)

    seed_T = fk(seed_q)
    x, y, z, roll, pitch, yaw = pose_to_xyz_rpy(seed_T)
    print(f"seed flange pose : xyz=({x:.3f}, {y:.3f}, {z:.3f}) "
          f"rpy=({math.degrees(roll):.1f}, {math.degrees(pitch):.1f}, "
          f"{math.degrees(yaw):.1f}) deg", file=sys.stderr)

    rng = np.random.default_rng(args.seed)
    kept, attempts = generate(seed_q, args.count, args.joint_spread, args.min_rot,
                              args.max_trans, None, rng,
                              down_cone_deg=args.down_cone)
    print(f"generated {len(kept)}/{args.count} poses in {attempts} samples",
          file=sys.stderr)
    if len(kept) < args.count:
        print("  (loosen --joint-spread / --max-trans or lower --min-rot for more)",
              file=sys.stderr)
    if not kept:
        return 1

    rots = [_rot_diff_deg(kept[0][1], T) for _, T in kept[1:]]
    ts = np.array([T[:3, 3] for _, T in kept])
    print(f"  orientation spread vs first pose: {min(rots):.1f}..{max(rots):.1f} deg",
          file=sys.stderr)
    print(f"  position spread: {np.ptp(ts, axis=0) * 1000} mm (x, y, z)", file=sys.stderr)

    text = to_yaml(kept, args.speed, args.settle)
    if args.out:
        with open(args.out, "w") as fh:
            fh.write(text)
        print(f"wrote {args.out}", file=sys.stderr)
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
