#!/usr/bin/env bash
# Give the two USB-CAN adapters STABLE names: can_follower and can_master.
#
#   sudo bash install_can_udev_rules.sh                 # detect and install
#   sudo bash install_can_udev_rules.sh --swap          # if the roles came out reversed
#   sudo bash install_can_udev_rules.sh --show          # print what is there now
#
# Why this exists
# ---------------
# Without a rule the kernel hands out can0/can1 in enumeration order, which can
# swap between boots. On a leader/follower rig that means a calibration run can
# silently command the WRONG ARM. Naming by the adapter's USB serial number
# fixes each name to a physical device, so it survives reboots AND replugging
# into a different port.
#
# The follower (the arm that moves and carries the wrist camera) is identified
# by its serial; see FOLLOWER_SERIAL below. Re-run with --swap if the roles are
# the other way round on your bench.
set -uo pipefail

RULES=/etc/udev/rules.d/99-piper-can.rules

# Recorded from this bench (2026-07-30). Adapters keep these forever.
FOLLOWER_SERIAL_DEFAULT="004000495246570520323934"

red() { printf '\033[31m%s\033[0m\n' "$*"; }
grn() { printf '\033[32m%s\033[0m\n' "$*"; }
ylw() { printf '\033[33m%s\033[0m\n' "$*"; }

list_adapters() {
    for ifc in $(ls /sys/class/net); do
        [ -e "/sys/class/net/$ifc/device" ] || continue
        dev=$(readlink -f "/sys/class/net/$ifc/device")
        usb=$(dirname "$dev")
        ser=$(cat "$usb/serial" 2>/dev/null) || continue
        vid=$(cat "$usb/idVendor" 2>/dev/null)
        pid=$(cat "$usb/idProduct" 2>/dev/null)
        [ "$vid$pid" = "1d50606f" ] || continue      # gs_usb CAN adapter
        echo "$ifc $ser $(basename "$dev")"
    done
}

if [ "${1:-}" = "--show" ]; then
    echo "CAN adapters present:"
    list_adapters | while read -r ifc ser port; do
        echo "  $ifc  serial=$ser  usb-port=$port"
    done
    [ -f "$RULES" ] && { echo; echo "installed rules ($RULES):"; cat "$RULES"; }
    exit 0
fi

if [ "$(id -u)" -ne 0 ]; then
    red "This must run as root (it writes $RULES)."
    echo "  sudo bash $0 ${*:-}"
    exit 1
fi

mapfile -t ADAPTERS < <(list_adapters)
if [ "${#ADAPTERS[@]}" -lt 2 ]; then
    red "Found ${#ADAPTERS[@]} USB-CAN adapter(s); this rig expects 2."
    echo "  Plug both in, then re-run. Present:"
    printf '    %s\n' "${ADAPTERS[@]:-<none>}"
    exit 1
fi

FOLLOWER_SERIAL="$FOLLOWER_SERIAL_DEFAULT"
if [ "${1:-}" = "--swap" ]; then
    # take the OTHER adapter as the follower
    for a in "${ADAPTERS[@]}"; do
        s=$(echo "$a" | awk '{print $2}')
        [ "$s" != "$FOLLOWER_SERIAL_DEFAULT" ] && FOLLOWER_SERIAL="$s"
    done
    ylw "--swap: follower is now serial $FOLLOWER_SERIAL"
fi

MASTER_SERIAL=""
for a in "${ADAPTERS[@]}"; do
    s=$(echo "$a" | awk '{print $2}')
    [ "$s" != "$FOLLOWER_SERIAL" ] && MASTER_SERIAL="$s"
done

if ! printf '%s\n' "${ADAPTERS[@]}" | awk '{print $2}' | grep -qx "$FOLLOWER_SERIAL"; then
    red "The recorded follower serial ($FOLLOWER_SERIAL) is not plugged in."
    echo "  Present serials:"
    printf '%s\n' "${ADAPTERS[@]}" | awk '{print "    " $2 "  (" $1 ")"}'
    echo "  Edit FOLLOWER_SERIAL_DEFAULT in this script, or use --swap."
    exit 1
fi

cat > "$RULES" <<EOF
# Piper hand-eye rig: stable CAN interface names, keyed to adapter serials.
# Generated by install_can_udev_rules.sh on $(date -Iseconds).
# can_follower = the arm that MOVES and carries the wrist camera.
SUBSYSTEM=="net", ACTION=="add", ATTRS{serial}=="$FOLLOWER_SERIAL", NAME="can_follower"
SUBSYSTEM=="net", ACTION=="add", ATTRS{serial}=="$MASTER_SERIAL", NAME="can_master"
EOF
grn "wrote $RULES"
sed 's/^/    /' "$RULES"

udevadm control --reload-rules
grn "rules reloaded"
echo
ylw "The names apply on the next plug event. Apply now without unplugging:"
echo "    sudo modprobe -r gs_usb && sudo modprobe gs_usb"
echo "  then bring the links up:"
echo "    bash $(dirname "$0")/can_setup.sh can_follower"
